// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-swimmers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_swimmers_default = defineTool({
  name: "search_swimmers",
  title: "Search swimmers",
  description: "Search enrolled swimmers by name (matches child first or last name). Returns swimmer name, parent name, email, swim level, and current status.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Name fragment to search for."),
    limit: z.number().int().min(1).max(50).default(20).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client(ctx);
    const like = `%${query}%`;
    const { data, error } = await supabase.from("swim_enrollments").select(
      "id, child_name, child_first_name, child_last_name, child_age, swim_level, status, parent_name, parent_email, parent_phone, session_id, created_at"
    ).or(
      `child_name.ilike.${like},child_first_name.ilike.${like},child_last_name.ilike.${like},parent_name.ilike.${like},parent_email.ilike.${like}`
    ).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-private-lessons.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_private_lessons_default = defineTool2({
  name: "list_upcoming_private_lessons",
  title: "List upcoming private lessons",
  description: "Return private lesson occurrences on or after the given start date (default today), up to the given number of days ahead. Includes swimmer, instructor, time, payment status, and charge status.",
  inputSchema: {
    fromDate: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("ISO date (YYYY-MM-DD). Defaults to today."),
    daysAhead: z2.number().int().min(1).max(60).default(14),
    limit: z2.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ fromDate, daysAhead, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client2(ctx);
    const start = fromDate ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const endDate = /* @__PURE__ */ new Date(start + "T00:00:00Z");
    endDate.setUTCDate(endDate.getUTCDate() + daysAhead);
    const end = endDate.toISOString().slice(0, 10);
    const { data, error } = await supabase.from("lesson_booking_occurrences").select(
      `id, occurrence_date, start_time_override, end_time_override, status, payment_status, charge_status,
         instructor_override_name,
         booking:lesson_bookings!inner(id, child_name, parent_name, parent_email, instructor_name, start_time, end_time, lesson_type, status)`
    ).gte("occurrence_date", start).lt("occurrence_date", end).neq("status", "cancelled").order("occurrence_date", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-active-sessions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_active_sessions_default = defineTool3({
  name: "list_active_sessions",
  title: "List active group sessions",
  description: "Return active group swim sessions with day, time, level, and enrollment counts vs capacity.",
  inputSchema: {
    swimLevel: z3.string().optional().describe("Optional level filter (e.g. Pearls, Sharks).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ swimLevel }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client3(ctx);
    let q = supabase.from("swim_sessions").select(
      "id, session_name, day_of_week, start_time, end_time, swim_level, max_students, registration_status, session_start_date, session_end_date, total_lessons, session_price"
    ).eq("is_active", true).order("session_start_date", { ascending: true });
    if (swimLevel) q = q.eq("swim_level", swimLevel);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-class-roster.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_class_roster_default = defineTool4({
  name: "get_class_roster",
  title: "Get class roster",
  description: "Return all active enrollments for a given swim_sessions.id, including swimmer, parent contact, payment status, and waiver status.",
  inputSchema: {
    sessionId: z4.string().uuid().describe("UUID of swim_sessions row.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sessionId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client4(ctx);
    const { data, error } = await supabase.from("swim_enrollments").select(
      "id, child_name, child_age, swim_level, status, parent_name, parent_email, parent_phone, payment_status, session_fee_status, waiver_signed_at, medical_notes, notes"
    ).eq("session_id", sessionId).neq("status", "cancelled").order("child_last_name", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-private-slots.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.23.8";

// src/lib/privateBooking-core.ts
function addMinutes(time, mins) {
  const [h, m] = time.split(":").map(Number);
  const total = h * 60 + m + mins;
  const hh = Math.floor(total / 60) % 24;
  const mm = total % 60;
  return `${String(hh).padStart(2, "0")}:${String(mm).padStart(2, "0")}`;
}
function normTime(t) {
  return t.length >= 5 ? t.substring(0, 5) : t;
}
function isoDate(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
function blockAppliesOnDate(b, dateStr, dow) {
  if (b.kind === "weekly") {
    if (b.day_of_week !== dow) return false;
    if (b.start_date && dateStr < b.start_date) return false;
    if (b.end_date && dateStr > b.end_date) return false;
    return true;
  }
  if (b.kind === "date_range") {
    if (b.start_date && dateStr < b.start_date) return false;
    if (b.end_date && dateStr > b.end_date) return false;
    if (b.day_of_week !== null && b.day_of_week !== dow) return false;
    return true;
  }
  return false;
}
function composeOpenSlots(input) {
  const instructorMap = Object.fromEntries(input.instructors.map((i) => [i.id, i.name]));
  const takenIntervals = [];
  for (const o of input.taken) {
    const startT = normTime(o.start_time || "");
    const endT = normTime(o.end_time || "");
    if (!o.instructor_id || !startT || !endT) continue;
    const [sh, sm] = startT.split(":").map(Number);
    const [eh, em] = endT.split(":").map(Number);
    takenIntervals.push({ instructor_id: o.instructor_id, date: o.occurrence_date, start: sh * 60 + sm, end: eh * 60 + em });
  }
  for (const h of input.holds) {
    const t = normTime(h.start_time);
    const [sh, sm] = t.split(":").map(Number);
    takenIntervals.push({ instructor_id: h.instructor_id, date: h.slot_date, start: sh * 60 + sm, end: sh * 60 + sm + 30 });
  }
  const availabilityBlocks = input.blocks.filter((b) => !b.is_blackout);
  const blackoutBlocks = input.blocks.filter((b) => b.is_blackout);
  const out = [];
  const cursor = new Date(input.fromDate);
  cursor.setHours(0, 0, 0, 0);
  for (let i = 0; i < input.weeks * 7; i++) {
    const d = new Date(cursor);
    d.setDate(d.getDate() + i);
    const dateStr = isoDate(d);
    const dow = d.getDay();
    const blackoutsToday = blackoutBlocks.filter((b) => blockAppliesOnDate(b, dateStr, dow)).map((b) => {
      const [sh, sm] = normTime(b.start_time).split(":").map(Number);
      const [eh, em] = normTime(b.end_time).split(":").map(Number);
      return { instructor_id: b.instructor_id, start: sh * 60 + sm, end: eh * 60 + em };
    });
    for (const blk of availabilityBlocks) {
      if (!blockAppliesOnDate(blk, dateStr, dow)) continue;
      let t = normTime(blk.start_time);
      const end = normTime(blk.end_time);
      const brkStart = blk.break_start_time ? normTime(blk.break_start_time) : null;
      const brkEnd = blk.break_end_time ? normTime(blk.break_end_time) : null;
      while (addMinutes(t, blk.slot_minutes) <= end) {
        const slotEnd = addMinutes(t, blk.slot_minutes);
        if (brkStart && brkEnd && t < brkEnd && slotEnd > brkStart) {
          t = brkEnd;
          continue;
        }
        const [th, tm] = t.split(":").map(Number);
        const [eh, em] = slotEnd.split(":").map(Number);
        const sMin = th * 60 + tm;
        const eMin = eh * 60 + em;
        const overlaps = takenIntervals.some(
          (iv) => iv.instructor_id === blk.instructor_id && iv.date === dateStr && sMin < iv.end && eMin > iv.start
        );
        const blackedOut = blackoutsToday.some(
          (bo) => bo.instructor_id === blk.instructor_id && sMin < bo.end && eMin > bo.start
        );
        if (!overlaps && !blackedOut) {
          out.push({
            instructor_id: blk.instructor_id,
            instructor_name: instructorMap[blk.instructor_id] || "Instructor",
            slot_date: dateStr,
            start_time: t,
            end_time: slotEnd
          });
        }
        t = slotEnd;
      }
    }
  }
  const seen = /* @__PURE__ */ new Set();
  return out.filter((s) => {
    const k = `${s.instructor_id}|${s.slot_date}|${s.start_time}`;
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
}

// src/lib/mcp/tools/list-open-private-slots.ts
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_open_private_slots_default = defineTool5({
  name: "list_open_private_slots",
  title: "List open private lesson slots",
  description: "List open 30-minute private lesson slots for a specific date. Uses the same availability computation as the public /book-private-lesson picker (instructor booking blocks minus existing bookings, active holds, and blackouts).",
  inputSchema: {
    date: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Target date (YYYY-MM-DD)."),
    instructorIds: z5.array(z5.string().uuid()).optional().describe("Optional list of instructor UUIDs to restrict to.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, instructorIds }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client5(ctx);
    const { data: instData, error: instErr } = await supabase.rpc("get_active_instructors_public");
    if (instErr) return { content: [{ type: "text", text: instErr.message }], isError: true };
    const instructors = instData || [];
    const allowed = new Set(instructorIds && instructorIds.length ? instructorIds : instructors.map((i) => i.id));
    const [blocksRes, occsRes, holdsRes] = await Promise.all([
      supabase.rpc("get_public_booking_blocks", { _instructor_ids: Array.from(allowed) }),
      supabase.rpc("get_public_taken_occurrences", { p_from_date: date, p_to_date: date }),
      supabase.rpc("get_active_slot_holds", { p_from_date: date, p_to_date: date, p_session_token: null })
    ]);
    for (const r of [blocksRes, occsRes, holdsRes]) {
      if (r.error) return { content: [{ type: "text", text: r.error.message }], isError: true };
    }
    const [y, m, d] = date.split("-").map(Number);
    const fromDate = new Date(y, m - 1, d);
    const slots = composeOpenSlots({
      fromDate,
      weeks: 1,
      instructors: instructors.filter((i) => allowed.has(i.id)),
      blocks: blocksRes.data || [],
      taken: occsRes.data || [],
      holds: holdsRes.data || []
    }).filter((s) => s.slot_date === date).sort(
      (a, b) => a.start_time === b.start_time ? a.instructor_name.localeCompare(b.instructor_name) : a.start_time.localeCompare(b.start_time)
    );
    return {
      content: [{ type: "text", text: JSON.stringify(slots, null, 2) }],
      structuredContent: { rows: slots, count: slots.length, date }
    };
  }
});

// src/lib/mcp/tools/list-past-private-families.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.23.8";
function client6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function normalizePhone(raw) {
  if (!raw) return null;
  const trimmed = raw.trim();
  if (!trimmed) return null;
  if (trimmed.startsWith("+")) {
    const d = "+" + trimmed.slice(1).replace(/\D/g, "");
    return d.length > 1 ? d : null;
  }
  const just = trimmed.replace(/\D/g, "");
  if (just.length === 10) return `+1${just}`;
  if (just.length === 11 && just.startsWith("1")) return `+${just}`;
  return just ? `+${just}` : null;
}
function isoDaysAgo(days) {
  const d = /* @__PURE__ */ new Date();
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString().slice(0, 10);
}
var list_past_private_families_default = defineTool6({
  name: "list_past_private_families",
  title: "List past private lesson families",
  description: "List distinct families who have had a private (or semi-private) lesson occurrence on or after sinceDate. Deduped by normalized phone number. Returns phone (E.164), parent name, child first names, and the most recent lesson date. Intended for outreach/blast lists.",
  inputSchema: {
    sinceDate: z6.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Only include families with a lesson on/after this date (default: 365 days ago)."),
    includeSemiPrivate: z6.boolean().default(true).describe("Include semi-private bookings alongside private."),
    limit: z6.number().int().min(1).max(1e3).default(500)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sinceDate, includeSemiPrivate, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client6(ctx);
    const since = sinceDate ?? isoDaysAgo(365);
    const types = includeSemiPrivate ? ["private", "semi-private"] : ["private"];
    const { data, error } = await supabase.from("lesson_booking_occurrences").select(
      `occurrence_date, status,
         booking:lesson_bookings!inner(id, lesson_type, status,
           parent_name, parent_first_name, parent_last_name, parent_phone,
           child_first_name, child_name)`
    ).gte("occurrence_date", since).neq("status", "cancelled").in("booking.lesson_type", types).neq("booking.status", "cancelled").not("booking.parent_phone", "is", null);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byPhone = /* @__PURE__ */ new Map();
    for (const r of data || []) {
      const b = r.booking;
      if (!b) continue;
      const phone = normalizePhone(b.parent_phone);
      if (!phone) continue;
      const parentName = b.parent_name || [b.parent_first_name, b.parent_last_name].filter(Boolean).join(" ") || "";
      const child = (b.child_first_name || "").trim() || ((b.child_name || "").split(" ")[0] || "").trim();
      const existing = byPhone.get(phone);
      if (existing) {
        if (child) existing._children.add(child);
        if (r.occurrence_date > existing.last_lesson_date) {
          existing.last_lesson_date = r.occurrence_date;
        }
        if (!existing.parent_name && parentName) existing.parent_name = parentName;
      } else {
        const children = /* @__PURE__ */ new Set();
        if (child) children.add(child);
        byPhone.set(phone, {
          phone,
          parent_name: parentName,
          childNames: [],
          last_lesson_date: r.occurrence_date,
          _children: children
        });
      }
    }
    const rows = Array.from(byPhone.values()).map((r) => ({
      phone: r.phone,
      parent_name: r.parent_name,
      childNames: Array.from(r._children).sort(),
      last_lesson_date: r.last_lesson_date
    })).sort((a, b) => a.last_lesson_date < b.last_lesson_date ? 1 : -1).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { rows, count: rows.length, since_date: since }
    };
  }
});

// src/lib/mcp/tools/send-private-openings-sms.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^3.23.8";
var RecipientSchema = z7.object({
  phone: z7.string().min(5),
  childNames: z7.array(z7.string()).optional().default([])
});
var send_private_openings_sms_default = defineTool7({
  name: "send_private_openings_sms",
  title: "Send private lesson openings SMS blast",
  description: "Send a bulk SMS blast (via TextMagic) to a list of past private-lesson families about open private slots on a specific date. Delegates to the existing admin-only send-bulk-outreach-sms edge function. REQUIRES confirm=true to actually send; without it the tool refuses. Use list_open_private_slots + list_past_private_families first, preview the template with the user, then call again with confirm=true.",
  inputSchema: {
    template: z7.string().min(5).max(1e3).describe(
      "SMS body. Supports {{childNames}} (per-recipient) and {{date}} placeholders resolved by the sender function."
    ),
    dateLabel: z7.string().min(1).describe("Human-readable date label, e.g. 'Sat Aug 30'. Passed as startDateLabel."),
    recipients: z7.array(RecipientSchema).min(1).max(500),
    reminderKind: z7.string().default("saturday_openings_sms"),
    confirm: z7.boolean().default(false).describe("Must be true to actually send. When false the tool returns without sending.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ template, dateLabel, recipients, reminderKind, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!confirm) {
      return {
        content: [
          {
            type: "text",
            text: `Refusing to send: confirm=false. Would text ${recipients.length} recipient(s) for ${dateLabel}. Re-call with confirm=true to actually send.`
          }
        ],
        structuredContent: {
          would_send: recipients.length,
          date_label: dateLabel,
          reminder_kind: reminderKind,
          preview_template: template
        }
      };
    }
    const url = `${process.env.SUPABASE_URL}/functions/v1/send-bulk-outreach-sms`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`
      },
      body: JSON.stringify({
        template,
        startDateLabel: dateLabel,
        recipients,
        reminderKind
      })
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `send-bulk-outreach-sms failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    let parsed = null;
    try {
      parsed = JSON.parse(text);
    } catch {
      parsed = { raw: text };
    }
    return {
      content: [{ type: "text", text }],
      structuredContent: parsed ?? { raw: text }
    };
  }
});

// src/lib/mcp/tools/list-standing-slots.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^3.23.8";
function client7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
var list_standing_slots_default = defineTool8({
  name: "list_standing_slots",
  title: "List standing membership slots",
  description: "List weekly membership standing slots with capacity, enrolled count, and spots left. Optional filters: program (kid_group/private/adult_group), swim level (white/red/yellow/blue/green), and day of week (0=Sunday..6=Saturday).",
  inputSchema: {
    program: z8.enum(["kid_group", "private", "adult_group"]).optional(),
    level: z8.enum(["white", "red", "yellow", "blue", "green"]).optional(),
    day: z8.number().int().min(0).max(6).optional().describe("0=Sunday..6=Saturday"),
    activeOnly: z8.boolean().default(true)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ program, level, day, activeOnly }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client7(ctx);
    let q = supabase.from("standing_slots").select(
      "id, plan_key, swim_level, day_of_week, start_time, end_time, capacity, location, active, instructor_id, instructors(name)"
    );
    if (activeOnly) q = q.eq("active", true);
    if (program) q = q.eq("plan_key", program);
    if (level) q = q.eq("swim_level", level);
    if (typeof day === "number") q = q.eq("day_of_week", day);
    const { data: slots, error } = await q.order("day_of_week").order("start_time");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const { data: plans } = await supabase.from("membership_plans").select("plan_key, name");
    const planNames = /* @__PURE__ */ new Map();
    for (const p of plans ?? []) planNames.set(p.plan_key, p.name ?? null);
    const slotIds = (slots ?? []).map((s) => s.id);
    const counts = /* @__PURE__ */ new Map();
    if (slotIds.length) {
      const { data: mems } = await supabase.from("memberships").select("standing_slot_id").in("standing_slot_id", slotIds).eq("status", "active");
      for (const m of mems ?? []) {
        counts.set(m.standing_slot_id, (counts.get(m.standing_slot_id) ?? 0) + 1);
      }
    }
    const rows = (slots ?? []).map((s) => {
      const enrolled = counts.get(s.id) ?? 0;
      return {
        id: s.id,
        plan_key: s.plan_key,
        program_name: planNames.get(s.plan_key) ?? null,
        swim_level: s.swim_level,
        instructor_name: s.instructors?.name ?? null,
        day_of_week: s.day_of_week,
        day_name: DAY_NAMES[s.day_of_week] ?? null,
        start_time: s.start_time,
        end_time: s.end_time,
        capacity: s.capacity,
        enrolled_count: enrolled,
        spots_left: Math.max(0, s.capacity - enrolled),
        active: s.active
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { rows }
    };
  }
});

// src/lib/mcp/tools/list-memberships.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^3.23.8";
function client8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var DAY_NAMES2 = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
var list_memberships_default = defineTool9({
  name: "list_memberships",
  title: "List memberships",
  description: "List memberships with swimmer, plan, standing-slot (day/time/level), status, billing period, and parent contact. Optional filters: status, plan_key, and a name/email query.",
  inputSchema: {
    status: z9.enum(["active", "past_due", "canceled", "paused", "pending"]).optional(),
    plan_key: z9.enum(["kid_group", "private", "adult_group"]).optional(),
    query: z9.string().trim().min(1).optional().describe("Optional fragment matched against swimmer name, parent name, or parent email."),
    limit: z9.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, plan_key, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client8(ctx);
    let q = supabase.from("memberships").select(
      `id, plan_key, status, start_date,
         child_first_name, child_last_name,
         parent_first_name, parent_last_name, parent_email, parent_phone,
         stripe_subscription_id, current_period_start, current_period_end,
         standing_slot_id,
         standing_slots(day_of_week, start_time, end_time, swim_level, instructors(name))`
    ).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (plan_key) q = q.eq("plan_key", plan_key);
    if (query) {
      const like = `%${query}%`;
      q = q.or(
        `child_first_name.ilike.${like},child_last_name.ilike.${like},parent_first_name.ilike.${like},parent_last_name.ilike.${like},parent_email.ilike.${like}`
      );
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (data ?? []).map((m) => m.id);
    const firstDates = /* @__PURE__ */ new Map();
    if (ids.length) {
      const { data: occs } = await supabase.from("membership_occurrences").select("membership_id, occurrence_date").in("membership_id", ids).order("occurrence_date", { ascending: true });
      for (const o of occs ?? []) {
        if (!firstDates.has(o.membership_id)) firstDates.set(o.membership_id, o.occurrence_date);
      }
    }
    const { data: plans } = await supabase.from("membership_plans").select("plan_key, name, monthly_price_cents");
    const planMap = /* @__PURE__ */ new Map();
    for (const p of plans ?? []) {
      planMap.set(p.plan_key, { name: p.name ?? null, monthly_price_cents: p.monthly_price_cents ?? null });
    }
    const rows = (data ?? []).map((m) => {
      const slot = m.standing_slots;
      const swimmer = [m.child_first_name, m.child_last_name].filter(Boolean).join(" ").trim();
      const parent = [m.parent_first_name, m.parent_last_name].filter(Boolean).join(" ").trim();
      const plan = planMap.get(m.plan_key);
      return {
        id: m.id,
        swimmer_name: swimmer || null,
        plan_key: m.plan_key,
        program: plan?.name ?? null,
        slot: slot ? {
          day_of_week: slot.day_of_week,
          day_name: DAY_NAMES2[slot.day_of_week] ?? null,
          start_time: slot.start_time,
          end_time: slot.end_time,
          swim_level: slot.swim_level,
          instructor_name: slot.instructors?.name ?? null
        } : null,
        status: m.status,
        start_date: m.start_date,
        first_lesson_date: firstDates.get(m.id) ?? null,
        monthly_price_cents: plan?.monthly_price_cents ?? null,
        stripe_subscription_id: m.stripe_subscription_id,
        current_period_start: m.current_period_start,
        current_period_end: m.current_period_end,
        next_charge_date: m.current_period_end,
        parent_name: parent || null,
        parent_email: m.parent_email,
        parent_phone: m.parent_phone
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { rows }
    };
  }
});

// src/lib/mcp/tools/get-membership.ts
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z10 } from "npm:zod@^3.23.8";
function client9(ctx) {
  return createClient9(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_membership_default = defineTool10({
  name: "get_membership",
  title: "Get membership detail",
  description: "Return the full membership record (swimmer, parent, plan, slot, consents, waiver_id) plus every scheduled membership_occurrence (date, time, instructor, status).",
  inputSchema: { id: z10.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client9(ctx);
    const { data: membership, error } = await supabase.from("memberships").select(
      `*,
         standing_slots(day_of_week, start_time, end_time, swim_level, location, instructors(name))`
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!membership) return { content: [{ type: "text", text: "Membership not found" }], isError: true };
    const { data: plan } = await supabase.from("membership_plans").select("plan_key, name, monthly_price_cents").eq("plan_key", membership.plan_key).maybeSingle();
    membership.membership_plans = plan ? { name: plan.name, monthly_price_cents: plan.monthly_price_cents } : null;
    const { data: occs, error: occErr } = await supabase.from("membership_occurrences").select("id, occurrence_date, start_time, end_time, status, closure_type, cancel_reason, instructor_id, instructors:instructor_id(name)").eq("membership_id", id).order("occurrence_date", { ascending: true });
    if (occErr) return { content: [{ type: "text", text: occErr.message }], isError: true };
    const payload = {
      membership,
      occurrences: (occs ?? []).map((o) => ({
        id: o.id,
        date: o.occurrence_date,
        start_time: o.start_time,
        end_time: o.end_time,
        status: o.status,
        closure_type: o.closure_type,
        cancel_reason: o.cancel_reason,
        instructor_name: o.instructors?.name ?? null
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-membership-billing-status.ts
import { createClient as createClient10 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z11 } from "npm:zod@^3.23.8";
function client10(ctx) {
  return createClient10(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function stripeKey(env) {
  const manual = process.env.STRIPE_API_KEY;
  const wantsLive = env === "live";
  if (manual && /^(sk|rk)_(test|live)_/.test(manual)) {
    const isLive = /^(sk|rk)_live_/.test(manual);
    if (isLive === wantsLive) return manual;
  }
  return env === "live" ? process.env.STRIPE_LIVE_API_KEY ?? null : process.env.STRIPE_SANDBOX_API_KEY ?? null;
}
async function stripeGet(env, path) {
  const key = stripeKey(env);
  if (!key) throw new Error(`No Stripe key configured for env=${env}`);
  const res = await fetch(`https://api.stripe.com/v1${path}`, {
    headers: { Authorization: `Bearer ${key}` }
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Stripe ${env} ${res.status}: ${body.slice(0, 300)}`);
  }
  return res.json();
}
var get_membership_billing_status_default = defineTool11({
  name: "get_membership_billing_status",
  title: "Get membership billing status",
  description: "Fetch live billing status from Stripe for a membership: subscription status, latest invoice status, and next charge date + amount. Defaults to the live environment; pass environment='sandbox' for test-mode subscriptions.",
  inputSchema: {
    id: z11.string().uuid(),
    environment: z11.enum(["live", "sandbox"]).default("live")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ id, environment }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client10(ctx);
    const { data: m, error } = await supabase.from("memberships").select("id, stripe_subscription_id, stripe_customer_id, status, current_period_start, current_period_end").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!m) return { content: [{ type: "text", text: "Membership not found" }], isError: true };
    if (!m.stripe_subscription_id) {
      const payload = {
        subscription_status: m.status,
        last_invoice_status: null,
        next_charge_date: m.current_period_end,
        next_charge_amount_cents: null,
        note: "No Stripe subscription linked to this membership."
      };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    }
    try {
      const sub = await stripeGet(environment, `/subscriptions/${m.stripe_subscription_id}`);
      const latestInvoiceId = typeof sub.latest_invoice === "string" ? sub.latest_invoice : sub.latest_invoice?.id;
      const invoice = latestInvoiceId ? await stripeGet(environment, `/invoices/${latestInvoiceId}`) : null;
      const nextTs = sub.current_period_end ?? null;
      const item = sub.items?.data?.[0];
      const nextAmount = item?.price?.unit_amount ?? null;
      const payload = {
        subscription_id: sub.id,
        subscription_status: sub.status,
        cancel_at_period_end: sub.cancel_at_period_end ?? false,
        current_period_start: sub.current_period_start ? new Date(sub.current_period_start * 1e3).toISOString() : null,
        current_period_end: sub.current_period_end ? new Date(sub.current_period_end * 1e3).toISOString() : null,
        next_charge_date: nextTs ? new Date(nextTs * 1e3).toISOString() : null,
        next_charge_amount_cents: nextAmount,
        last_invoice_status: invoice?.status ?? null,
        last_invoice_amount_paid_cents: invoice?.amount_paid ?? null,
        last_invoice_hosted_url: invoice?.hosted_invoice_url ?? null
      };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: e.message }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/read-repo-file.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z12 } from "npm:zod@^3.23.8";
var REPO = "simplysydnee/aquatic-dream";
var read_repo_file_default = defineTool12({
  name: "read_repo_file",
  title: "Read repo file",
  description: "Fetch the raw text of a file from the aquatic-dream GitHub repository (default branch). Read-only. Example path: 'supabase/functions/create-membership-checkout/index.ts'.",
  inputSchema: {
    path: z12.string().trim().min(1).max(500).describe("Repo-relative file path, e.g. 'src/lib/mcp/index.ts'."),
    ref: z12.string().trim().min(1).max(200).optional().describe("Optional branch, tag, or commit SHA. Defaults to the repo's default branch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ path, ref }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      return {
        content: [{ type: "text", text: "GITHUB_TOKEN is not configured on the server." }],
        isError: true
      };
    }
    const cleanPath = path.replace(/^\/+/, "");
    const qs = ref ? `?ref=${encodeURIComponent(ref)}` : "";
    const url = `https://api.github.com/repos/${REPO}/contents/${cleanPath}${qs}`;
    const res = await fetch(url, {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github.raw",
        "User-Agent": "aquatic-dreams-mcp"
      }
    });
    const body = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `GitHub responded ${res.status}: ${body}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: body }],
      structuredContent: { path: cleanPath, ref: ref ?? null, content: body }
    };
  }
});

// src/lib/mcp/tools/list-repo-dir.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z13 } from "npm:zod@^3.23.8";
var REPO2 = "simplysydnee/aquatic-dream";
var list_repo_dir_default = defineTool13({
  name: "list_repo_dir",
  title: "List repo directory",
  description: "List file and folder entries at a path in the aquatic-dream GitHub repository (default branch). Read-only. Use path='' for the repo root.",
  inputSchema: {
    path: z13.string().trim().max(500).default("").describe("Repo-relative directory path. Empty string for repo root."),
    ref: z13.string().trim().min(1).max(200).optional().describe("Optional branch, tag, or commit SHA. Defaults to the repo's default branch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ path, ref }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      return {
        content: [{ type: "text", text: "GITHUB_TOKEN is not configured on the server." }],
        isError: true
      };
    }
    const cleanPath = path.replace(/^\/+|\/+$/g, "");
    const qs = ref ? `?ref=${encodeURIComponent(ref)}` : "";
    const url = `https://api.github.com/repos/${REPO2}/contents/${cleanPath}${qs}`;
    const res = await fetch(url, {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "aquatic-dreams-mcp"
      }
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `GitHub responded ${res.status}: ${text}` }],
        isError: true
      };
    }
    let parsed;
    try {
      parsed = JSON.parse(text);
    } catch {
      return {
        content: [{ type: "text", text: `Unexpected GitHub response: ${text}` }],
        isError: true
      };
    }
    if (!Array.isArray(parsed)) {
      return {
        content: [
          {
            type: "text",
            text: `Path is not a directory. Use read_repo_file for files. Raw: ${text}`
          }
        ],
        isError: true
      };
    }
    const entries = parsed.map((e) => ({ name: e.name, path: e.path, type: e.type, size: e.size ?? null })).sort((a, b) => {
      if (a.type !== b.type) return a.type === "dir" ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
    return {
      content: [{ type: "text", text: JSON.stringify(entries, null, 2) }],
      structuredContent: { path: cleanPath, ref: ref ?? null, entries }
    };
  }
});

// src/lib/mcp/tools/cancel-membership.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z14 } from "npm:zod@^3.23.8";

// src/lib/mcp/tools/_client.ts
import { createClient as createClient11 } from "npm:@supabase/supabase-js@^2.98.0";
function adminClient(ctx) {
  return createClient11(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthed() {
  return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
}
function refuseUnconfirmed(summary, preview) {
  return {
    content: [
      {
        type: "text",
        text: `Refusing: confirm=false. ${summary} Re-call with confirm=true to execute.`
      }
    ],
    structuredContent: { would_do: summary, preview }
  };
}
function errResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function okResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/cancel-membership.ts
var cancel_membership_default = defineTool14({
  name: "cancel_membership",
  title: "Cancel membership",
  description: "Mark a membership as canceled in the database and record a cancellation row. Does NOT cancel the Stripe subscription \u2014 do that separately in Stripe if needed. Requires confirm=true.",
  inputSchema: {
    id: z14.string().uuid(),
    effective_date: z14.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Cancellation effective date (YYYY-MM-DD). Defaults to today."),
    reason: z14.string().max(100).optional(),
    reason_detail: z14.string().max(1e3).optional(),
    confirm: z14.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id, effective_date, reason, reason_detail, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const effective = effective_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    if (!confirm) {
      return refuseUnconfirmed(`Would cancel membership ${id} effective ${effective}.`, {
        id,
        effective,
        reason
      });
    }
    const supabase = adminClient(ctx);
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const { error: upErr } = await supabase.from("memberships").update({
      status: "canceled",
      cancel_requested_at: nowIso,
      cancel_effective_date: effective
    }).eq("id", id);
    if (upErr) return errResult(upErr.message);
    const { error: insErr } = await supabase.from("membership_cancellations").insert({
      membership_id: id,
      effective_date: effective,
      reason: reason ?? null,
      reason_detail: reason_detail ?? null
    });
    if (insErr) return errResult(`membership updated, but cancellation row failed: ${insErr.message}`);
    return okResult({ id, status: "canceled", effective_date: effective });
  }
});

// src/lib/mcp/tools/set-membership-status.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z15 } from "npm:zod@^3.23.8";
var set_membership_status_default = defineTool15({
  name: "set_membership_status",
  title: "Pause or resume membership",
  description: "Set a membership's status to 'paused' or 'active'. Use cancel_membership to cancel. Requires confirm=true.",
  inputSchema: {
    id: z15.string().uuid(),
    status: z15.enum(["paused", "active"]),
    confirm: z15.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, status, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    if (!confirm) return refuseUnconfirmed(`Would set membership ${id} status to ${status}.`, { id, status });
    const supabase = adminClient(ctx);
    const { data, error } = await supabase.from("memberships").update({ status }).eq("id", id).select("id, status").maybeSingle();
    if (error) return errResult(error.message);
    if (!data) return errResult("Membership not found");
    return okResult(data);
  }
});

// src/lib/mcp/tools/move-membership-slot.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z16 } from "npm:zod@^3.23.8";
var move_membership_slot_default = defineTool16({
  name: "move_membership_slot",
  title: "Move membership to a different standing slot",
  description: "Reassign a membership to a different standing slot (day/time/level). Verifies destination slot exists, is active, matches plan_key, and has capacity. Requires confirm=true.",
  inputSchema: {
    membership_id: z16.string().uuid(),
    new_standing_slot_id: z16.string().uuid(),
    confirm: z16.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ membership_id, new_standing_slot_id, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = adminClient(ctx);
    const { data: m, error: mErr } = await supabase.from("memberships").select("id, plan_key, standing_slot_id, status").eq("id", membership_id).maybeSingle();
    if (mErr) return errResult(mErr.message);
    if (!m) return errResult("Membership not found");
    const { data: slot, error: sErr } = await supabase.from("standing_slots").select("id, plan_key, is_active, capacity, day_of_week, start_time, end_time, swim_level").eq("id", new_standing_slot_id).maybeSingle();
    if (sErr) return errResult(sErr.message);
    if (!slot) return errResult("Destination slot not found");
    if (!slot.is_active) return errResult("Destination slot is not active");
    if (slot.plan_key !== m.plan_key)
      return errResult(`Plan mismatch: membership is ${m.plan_key}, slot is ${slot.plan_key}`);
    const { count, error: cErr } = await supabase.from("memberships").select("id", { count: "exact", head: true }).eq("standing_slot_id", new_standing_slot_id).in("status", ["active", "past_due", "pending"]);
    if (cErr) return errResult(cErr.message);
    const enrolled = count ?? 0;
    if (enrolled >= (slot.capacity ?? 0))
      return errResult(`Destination slot is full (${enrolled}/${slot.capacity})`);
    if (!confirm) {
      return refuseUnconfirmed(
        `Would move membership ${membership_id} from slot ${m.standing_slot_id} to ${new_standing_slot_id}.`,
        { destination: slot, current_enrolled: enrolled }
      );
    }
    const { data, error } = await supabase.from("memberships").update({ standing_slot_id: new_standing_slot_id }).eq("id", membership_id).select("id, standing_slot_id").maybeSingle();
    if (error) return errResult(error.message);
    return okResult({ ...data, destination_slot: slot });
  }
});

// src/lib/mcp/tools/update-standing-slot.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z17 } from "npm:zod@^3.23.8";
var update_standing_slot_default = defineTool17({
  name: "update_standing_slot",
  title: "Update standing slot",
  description: "Update editable fields on a standing slot (capacity, day_of_week, start_time, end_time, swim_level, instructor_id, location, is_active). Only provided fields change. Requires confirm=true.",
  inputSchema: {
    id: z17.string().uuid(),
    capacity: z17.number().int().min(0).max(50).optional(),
    day_of_week: z17.number().int().min(0).max(6).optional(),
    start_time: z17.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
    end_time: z17.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
    swim_level: z17.enum(["white", "red", "yellow", "blue", "green"]).nullable().optional(),
    instructor_id: z17.string().uuid().nullable().optional(),
    location: z17.string().max(200).nullable().optional(),
    is_active: z17.boolean().optional(),
    confirm: z17.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { id, confirm, ...rest } = input;
    const updates = Object.fromEntries(Object.entries(rest).filter(([, v]) => v !== void 0));
    if (Object.keys(updates).length === 0) return errResult("No fields provided to update");
    if (!confirm) {
      return refuseUnconfirmed(`Would update standing slot ${id}.`, { id, updates });
    }
    const supabase = adminClient(ctx);
    const { data, error } = await supabase.from("standing_slots").update(updates).eq("id", id).select("*").maybeSingle();
    if (error) return errResult(error.message);
    if (!data) return errResult("Standing slot not found");
    return okResult(data);
  }
});

// src/lib/mcp/tools/cancel-private-lesson-occurrence.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z18 } from "npm:zod@^3.23.8";
var cancel_private_lesson_occurrence_default = defineTool18({
  name: "cancel_private_lesson_occurrence",
  title: "Cancel a private lesson occurrence",
  description: "Mark a single lesson_booking_occurrences row as cancelled (admin cancel \u2014 skips charge). Requires confirm=true.",
  inputSchema: {
    occurrence_id: z18.string().uuid(),
    reason: z18.string().max(500).optional(),
    skip_charge: z18.boolean().default(true).describe("If true (default), sets charge_status to 'skipped' so the family is not billed."),
    confirm: z18.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ occurrence_id, reason, skip_charge, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    if (!confirm) {
      return refuseUnconfirmed(`Would cancel private lesson occurrence ${occurrence_id}.`, {
        occurrence_id,
        reason,
        skip_charge
      });
    }
    const supabase = adminClient(ctx);
    const updates = {
      status: "cancelled",
      cancelled_at: (/* @__PURE__ */ new Date()).toISOString(),
      cancel_reason: reason ?? "Admin cancellation via MCP"
    };
    if (skip_charge) updates.charge_status = "skipped";
    const { data, error } = await supabase.from("lesson_booking_occurrences").update(updates).eq("id", occurrence_id).select("id, status, cancel_reason, charge_status, occurrence_date").maybeSingle();
    if (error) return errResult(error.message);
    if (!data) return errResult("Occurrence not found");
    return okResult(data);
  }
});

// src/lib/mcp/tools/reassign-private-lesson-instructor.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z19 } from "npm:zod@^3.23.8";
var reassign_private_lesson_instructor_default = defineTool19({
  name: "reassign_private_lesson_instructor",
  title: "Reassign instructor on a private lesson occurrence",
  description: "Override the instructor on a single lesson_booking_occurrences row (does not change other occurrences in the series). Requires confirm=true.",
  inputSchema: {
    occurrence_id: z19.string().uuid(),
    new_instructor_id: z19.string().uuid(),
    confirm: z19.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ occurrence_id, new_instructor_id, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = adminClient(ctx);
    const { data: instructor, error: iErr } = await supabase.from("instructors").select("id, name").eq("id", new_instructor_id).maybeSingle();
    if (iErr) return errResult(iErr.message);
    if (!instructor) return errResult("Instructor not found");
    if (!confirm) {
      return refuseUnconfirmed(
        `Would reassign occurrence ${occurrence_id} to ${instructor.name}.`,
        { occurrence_id, instructor }
      );
    }
    const { data, error } = await supabase.from("lesson_booking_occurrences").update({
      instructor_override_id: instructor.id,
      instructor_override_name: instructor.name
    }).eq("id", occurrence_id).select("id, occurrence_date, instructor_override_id, instructor_override_name").maybeSingle();
    if (error) return errResult(error.message);
    if (!data) return errResult("Occurrence not found");
    return okResult(data);
  }
});

// src/lib/mcp/tools/reschedule-private-lesson-occurrence.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z20 } from "npm:zod@^3.23.8";
var reschedule_private_lesson_occurrence_default = defineTool20({
  name: "reschedule_private_lesson_occurrence",
  title: "Reschedule a private lesson occurrence",
  description: "Move a single lesson_booking_occurrences row to a new date and/or start/end time. Does NOT check instructor availability \u2014 verify with list_open_private_slots first. Requires confirm=true.",
  inputSchema: {
    occurrence_id: z20.string().uuid(),
    new_date: z20.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
    new_start_time: z20.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
    new_end_time: z20.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
    confirm: z20.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ occurrence_id, new_date, new_start_time, new_end_time, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const updates = {};
    if (new_date) updates.occurrence_date = new_date;
    if (new_start_time) updates.start_time_override = new_start_time;
    if (new_end_time) updates.end_time_override = new_end_time;
    if (Object.keys(updates).length === 0) return errResult("Provide at least one of new_date, new_start_time, new_end_time");
    if (!confirm) {
      return refuseUnconfirmed(`Would reschedule occurrence ${occurrence_id}.`, {
        occurrence_id,
        updates
      });
    }
    const supabase = adminClient(ctx);
    const { data, error } = await supabase.from("lesson_booking_occurrences").update(updates).eq("id", occurrence_id).select("id, occurrence_date, start_time_override, end_time_override, status").maybeSingle();
    if (error) return errResult(error.message);
    if (!data) return errResult("Occurrence not found");
    return okResult(data);
  }
});

// src/lib/mcp/tools/update-swim-enrollment.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z21 } from "npm:zod@^3.23.8";
var update_swim_enrollment_default = defineTool21({
  name: "update_swim_enrollment",
  title: "Update a swim enrollment",
  description: "Update editable fields on a swim_enrollments row: parent_phone, swim_level, status, session_fee_status, session_fee_payment_method, session_fee_payment_reference. Only provided fields change. Requires confirm=true.",
  inputSchema: {
    id: z21.string().uuid(),
    parent_phone: z21.string().min(5).max(30).optional(),
    swim_level: z21.enum(["white", "red", "yellow", "blue", "green"]).optional(),
    status: z21.enum(["active", "cancelled", "pending", "waitlist"]).optional(),
    session_fee_status: z21.enum(["paid", "unpaid", "refunded", "waived"]).optional(),
    session_fee_payment_method: z21.string().max(50).optional(),
    session_fee_payment_reference: z21.string().max(200).optional(),
    confirm: z21.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { id, confirm, ...rest } = input;
    const updates = Object.fromEntries(Object.entries(rest).filter(([, v]) => v !== void 0));
    if (Object.keys(updates).length === 0) return errResult("No fields provided to update");
    if (!confirm) {
      return refuseUnconfirmed(`Would update swim_enrollments ${id}.`, { id, updates });
    }
    const supabase = adminClient(ctx);
    const { data, error } = await supabase.from("swim_enrollments").update(updates).eq("id", id).select("id, parent_phone, swim_level, status, session_fee_status, session_fee_payment_method, session_fee_payment_reference").maybeSingle();
    if (error) return errResult(error.message);
    if (!data) return errResult("Enrollment not found");
    return okResult(data);
  }
});

// src/lib/mcp/tools/complete-membership-checkout.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z22 } from "npm:zod@^3.23.8";
var complete_membership_checkout_default = defineTool22({
  name: "complete_membership_checkout",
  title: "Complete membership checkout",
  description: "Recovery tool: finish a membership signup from its Stripe checkout session id (cs_...). Creates the Stripe subscription if missing, writes the membership row, generates lesson occurrences, and sends the welcome message. Safe to re-run \u2014 it is idempotent. Requires confirm=true.",
  inputSchema: {
    session_id: z22.string().regex(/^cs_(test|live)_[A-Za-z0-9]+$/).describe("Stripe Checkout session id from the membership signup."),
    confirm: z22.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
  handler: async ({ session_id, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    if (!confirm) {
      return refuseUnconfirmed(
        `Would complete the membership for checkout session ${session_id}.`,
        { session_id }
      );
    }
    try {
      const res = await fetch(`${process.env.SUPABASE_URL}/functions/v1/confirm-membership-checkout`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: process.env.SUPABASE_ANON_KEY,
          Authorization: `Bearer ${ctx.getToken()}`
        },
        body: JSON.stringify({ sessionId: session_id })
      });
      const text = await res.text();
      let body;
      try {
        body = JSON.parse(text);
      } catch {
        body = { raw: text.slice(0, 500) };
      }
      if (!res.ok) {
        const message = typeof body === "object" && body !== null && "error" in body ? String(body.error) : text.slice(0, 300);
        return errResult(`Membership completion failed (${res.status}): ${message}`);
      }
      return okResult(body);
    } catch (error) {
      return errResult(error instanceof Error ? error.message : String(error));
    }
  }
});

// src/lib/mcp/tools/run-readonly-sql.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z23 } from "npm:zod@^3.23.8";
var FORBIDDEN = /(^|[^a-z_])(insert|update|delete|merge|alter|drop|create|grant|revoke|truncate|comment|vacuum|analyze|copy|call|do|set|reset|refresh|reindex|cluster|listen|notify|lock|prepare|execute|begin|commit|rollback|savepoint)([^a-z_]|$)/i;
var run_readonly_sql_default = defineTool23({
  name: "run_readonly_sql",
  title: "Run read-only SQL",
  description: "Run a single read-only SELECT (or WITH ... SELECT) query against the database and return the rows. Writes and DDL are rejected and the query runs inside a read-only transaction. Admin only. Results are capped.",
  inputSchema: {
    query: z23.string().trim().min(1).max(1e4).describe("A single SELECT or WITH ... SELECT statement. No semicolon-separated statements."),
    limit: z23.number().int().min(1).max(1e3).default(200).describe("Maximum number of rows to return (default 200, max 1000).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const q = query.trim().replace(/;\s*$/, "");
    if (q.includes(";")) return errResult("Multiple statements are not allowed.");
    if (!/^(select|with)\s/i.test(q)) {
      return errResult("Only a single SELECT (or WITH ... SELECT) statement is allowed.");
    }
    if (FORBIDDEN.test(q)) {
      return errResult("Query contains a disallowed keyword; only read-only SELECT queries are permitted.");
    }
    const { data, error } = await adminClient(ctx).rpc("mcp_run_readonly_sql", {
      _query: q,
      _limit: limit
    });
    if (error) return errResult(error.message);
    return okResult(data);
  }
});

// src/lib/mcp/tools/describe-table.ts
import { defineTool as defineTool24 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z24 } from "npm:zod@^3.23.8";
var describe_table_default = defineTool24({
  name: "describe_table",
  title: "Describe table",
  description: "Return a table's columns (name, data type, nullability, default), enum labels for USER-DEFINED types, and both outgoing and incoming foreign keys. Read-only, admin only.",
  inputSchema: {
    table_name: z24.string().trim().min(1).max(120).describe("Table name, e.g. 'memberships'."),
    schema: z24.string().trim().min(1).max(120).default("public").describe("Schema name (default 'public').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ table_name, schema }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await adminClient(ctx).rpc("mcp_describe_table", {
      _table_name: table_name,
      _schema: schema
    });
    if (error) return errResult(error.message);
    return okResult(data);
  }
});

// src/lib/mcp/tools/search-repo.ts
import { defineTool as defineTool25 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z25 } from "npm:zod@^3.23.8";
var REPO3 = "simplysydnee/aquatic-dream";
var MAX_FILES_SCANNED = 25;
var search_repo_default = defineTool25({
  name: "search_repo",
  title: "Search repo",
  description: "Search the aquatic-dream GitHub repository for a pattern and return file path, line number, and the matching line. Read-only. Results are capped.",
  inputSchema: {
    pattern: z25.string().trim().min(2).max(200).describe("Text or regular expression to match against file lines."),
    path_prefix: z25.string().trim().max(300).optional().describe("Optional repo-relative path prefix to restrict results, e.g. 'src/lib/mcp'."),
    max_results: z25.number().int().min(1).max(200).default(50).describe("Maximum number of matching lines to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ pattern, path_prefix, max_results }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      return {
        content: [{ type: "text", text: "GITHUB_TOKEN is not configured on the server." }],
        isError: true
      };
    }
    let regex;
    try {
      regex = new RegExp(pattern, "i");
    } catch {
      return {
        content: [{ type: "text", text: `Invalid regular expression: ${pattern}` }],
        isError: true
      };
    }
    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "User-Agent": "aquatic-dreams-mcp"
    };
    const literal = pattern.replace(/[\\^$.*+?()[\]{}|]/g, " ").trim() || pattern;
    const prefix = (path_prefix ?? "").replace(/^\/+|\/+$/g, "");
    const q = [`${literal} repo:${REPO3}`, prefix ? `path:${prefix}` : ""].filter(Boolean).join(" ");
    const searchRes = await fetch(
      `https://api.github.com/search/code?per_page=${MAX_FILES_SCANNED}&q=${encodeURIComponent(q)}`,
      { headers }
    );
    const searchText = await searchRes.text();
    if (!searchRes.ok) {
      return {
        content: [{ type: "text", text: `GitHub search responded ${searchRes.status}: ${searchText}` }],
        isError: true
      };
    }
    let items = [];
    try {
      items = JSON.parse(searchText).items ?? [];
    } catch {
      return {
        content: [{ type: "text", text: `Unexpected GitHub response: ${searchText.slice(0, 500)}` }],
        isError: true
      };
    }
    const files = items.map((i) => i.path).filter((p) => prefix ? p.startsWith(prefix) : true).slice(0, MAX_FILES_SCANNED);
    const matches = [];
    for (const path of files) {
      if (matches.length >= max_results) break;
      const res = await fetch(
        `https://api.github.com/repos/${REPO3}/contents/${encodeURI(path)}`,
        { headers: { ...headers, Accept: "application/vnd.github.raw" } }
      );
      if (!res.ok) continue;
      const body = await res.text();
      const lines = body.split("\n");
      for (let i = 0; i < lines.length; i++) {
        if (regex.test(lines[i])) {
          matches.push({ path, line: i + 1, text: lines[i].slice(0, 400) });
          if (matches.length >= max_results) break;
        }
      }
    }
    const payload = {
      pattern,
      path_prefix: prefix || null,
      files_scanned: files.length,
      match_count: matches.length,
      truncated: matches.length >= max_results,
      matches
    };
    return {
      content: [
        {
          type: "text",
          text: matches.length === 0 ? "No matches found." : matches.map((m) => `${m.path}:${m.line}: ${m.text}`).join("\n")
        }
      ],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jilrijklnehbfuulykty";
var mcp_default = defineMcp({
  name: "aquatic-dreams-mcp",
  title: "Aquatic Dreams Admin",
  version: "0.1.0",
  instructions: "Read-only tools for Aquatic Dreams Swim School staff. Use these to look up swimmers, active group sessions, class rosters, and upcoming private lessons. Data returned is scoped to the signed-in admin's permissions via row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_swimmers_default,
    list_upcoming_private_lessons_default,
    list_active_sessions_default,
    get_class_roster_default,
    list_open_private_slots_default,
    list_past_private_families_default,
    send_private_openings_sms_default,
    list_standing_slots_default,
    list_memberships_default,
    get_membership_default,
    get_membership_billing_status_default,
    read_repo_file_default,
    list_repo_dir_default,
    cancel_membership_default,
    set_membership_status_default,
    move_membership_slot_default,
    update_standing_slot_default,
    cancel_private_lesson_occurrence_default,
    reassign_private_lesson_instructor_default,
    reschedule_private_lesson_occurrence_default,
    update_swim_enrollment_default,
    complete_membership_checkout_default,
    run_readonly_sql_default,
    describe_table_default,
    search_repo_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
